#!/bin/bash
#asking var value from users  according caommnd line it will print 
case $1 in
     req*)
         echo "it's requirement or request"
         ;;
     meet*)
         echo "it's meeting"
         ;;
     *)
        echo "its default statement"
esac

