#!/bin/bash
#5 mathematicoperators using paranthesious ()
num1=25
num2=5
echo "$(( $num1 + $num2))"
echo "$(( $num1 - $num2))"
echo "$(( $num1 * $num2))"
echo "$(( $num1 % $num2))"
echo "$(( $num1 / $num2))"